remote_theme: mmistakes/minimal-mistakes
title: Galactic 
include: ["_pages"]

author: 
 name: "JRain"
 avatar: "e9c8fbd5c3df3dd0d76a96697c364fb7--unicorn-club-moustache.jpg"
 bio: "Everyone should own a pet mustache."
